version: '3.8'

services:
  backend-server:
    image: kaetaro13/beats-game-server
    container_name: backend-server
    ports:
      - "127.0.0.1:8081:8085"
    env_file:
      - ./.env
    networks:
      - ann-network
    restart: always

  game-server:
    image: kaetaro13/godot-server:latest
    container_name: game-server
    ports:
      - "127.0.0.1:9087:8087"
    networks:
      - ann-network
    restart: always

  edgedb:
    image: edgedb/edgedb
    container_name: edgedb
    environment:
      - EDGEDB_SERVER_PASSWORD=${EDGE_DB_PASSWORD}
      - EDGEDB_SERVER_TLS_CERT_MODE=generate_self_signed
    volumes:
      - /my/data/directory:/var/lib/edgedb/data
    networks:
      - ann-network
    ports:
      - "5656:5656"
    restart: always

networks:
  ann-network:
    driver: bridge
