version: '3.8'

services:
  app1:
    image: kaetaro13/beats-main-server
    ports:
      - "8081:8085"
    env_file:
      - ./.env
    networks:
      - ann-network
  
  app2:
    image: kaetaro13/beats-main-server
    ports:
      - "8082:8085"
    env_file:
      - ./.env
    networks:
      - ann-network