services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    command: keydb-server /etc/keydb/keydb.conf --requirepass ${KEYDB_PASSWORD} --server-threads 1
    ports:
      - "127.0.0.1:6379:6379"  # Accessible only from the host
    networks:
      - ann-network
    restart: always

  backend-server:
    image: kaetaro13/beats-game-server
    container_name: backend-server
    ports:
      - "127.0.0.1:8081:8085"  # Accessible only from the host
    env_file:
      - ./.env
    networks:
      - ann-network
    restart: always
    
  game-server:
    image: kaetaro13/godot-server:latest
    container_name: game-server
    ports:
      - "127.0.0.1:8090:8087"  # Accessible only from the host
    networks:
      - ann-network
    restart: always

networks:
  ann-network:
    driver: bridge





#  docker run \
#          --name edgedb \
#          -e EDGEDB_SERVER_PASSWORD=edgedb12345678\
#          -e EDGEDB_SERVER_TLS_CERT_MODE=generate_self_signed \
#          -e EDGEDB_SERVER_USER=gmetarave \
#          -e EDGEDB_SERVER_SECURITY=insecure_dev_mode \
#          -e EDGEDB_SERVER_HTTP_ENDPOINT_SECURITY=1 \
#          -v edgedb-data:/var/lib/edgedb/data \
#          --network ann-network \
#          -p 127.0.0.1:5656:5656 \
#          -d \
#          --restart always \
#          edgedb/edgedb

